import { expect, test } from "@playwright/test";
import { copyFile, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fixturePath } from "../tests/fixture-path";

test("exercise detail, lazy video, local notes, timer and workout note work on a phone", async ({ page, context }, testInfo) => {
  const folder = await mkdtemp(join(tmpdir(), "treino-exercise-context-"));
  const workbook = join(folder, "TREINO 1 JONATHA.xlsx");
  await copyFile(fixturePath("TREINO 1 JONATHA.xlsx"), workbook);
  try {
    await page.goto("/plans/");
    await page.getByRole("button", { name: /Add training/ }).tap();
    const direct = await page.evaluate(() => window.isSecureContext && "showOpenFilePicker" in window);
    const chooser = page.waitForEvent("filechooser");
    await page.getByRole("button", { name: direct ? "Import as safe copy" : "Choose workbook" }).tap();
    await (await chooser).setFiles(workbook);
    await expect(page.getByRole("heading", { name: "Training ready" })).toBeVisible();
    await page.locator(".import-review").getByRole("button", { name: /Use this training/ }).tap();
    await page.getByRole("button", { name: "Start workout" }).first().tap();
    const squat = page.locator(".exercise-card").filter({ has: page.getByRole("heading", { name: /Agachamento goblet/i }) });
    await squat.getByRole("button", { name: "Details" }).tap();
    const detail = page.getByRole("dialog", { name: /Agachamento goblet/i });
    await expect(detail).toBeVisible();
    await expect(detail.getByText("3X8-10")).toBeVisible();
    await expect(detail.locator("iframe")).toHaveCount(0);
    await page.screenshot({ path: testInfo.outputPath("exercise-overview.png"), animations: "disabled" });
    await detail.getByRole("tab", { name: "History" }).tap();
    await expect(detail.getByText(/recorded load history/)).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath("exercise-history.png"), animations: "disabled" });
    await detail.getByRole("tab", { name: "Notes" }).tap();
    const portrait = page.viewportSize()!;
    await detail.getByRole("textbox", { name: "EXERCISE NOTE" }).fill("Long note ".repeat(80));
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
    await detail.getByRole("textbox", { name: "EXERCISE NOTE" }).fill("Seat position 4; narrower grip next time.");
    await page.setViewportSize({ ...portrait, height: 440 });
    await detail.getByRole("textbox", { name: "EXERCISE NOTE" }).focus();
    await detail.getByRole("button", { name: "Save note" }).tap();
    await page.setViewportSize(portrait);
    await expect(detail.getByText("Note saved on this device.")).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath("exercise-note.png"), animations: "disabled" });
    await detail.getByRole("button", { name: "Close exercise details" }).tap();
    await page.reload();
    await squat.getByRole("button", { name: "Details" }).tap();
    await detail.getByRole("tab", { name: "Notes" }).tap();
    await expect(detail.getByRole("textbox", { name: "EXERCISE NOTE" })).toHaveValue("Seat position 4; narrower grip next time.");
    await detail.getByRole("button", { name: "Close exercise details" }).tap();
    await context.setOffline(true);
    await squat.getByRole("button", { name: "Details" }).tap();
    await detail.getByRole("button", { name: "Watch execution" }).tap();
    await expect(detail.getByText("Video requires an internet connection.")).toBeVisible();
    await expect(detail.getByRole("link", { name: /Open in YouTube/ })).toHaveAttribute("href", /youtube\.com\/watch\?v=/);
    await expect(detail.locator("iframe")).toHaveCount(0);
    await detail.getByRole("button", { name: "Close exercise details" }).tap();
    await context.setOffline(false);
    await page.route("https://www.youtube-nocookie.com/**", (route) => route.fulfill({ status: 200, contentType: "text/html", body: "<html><body>Video test</body></html>" }));
    await squat.getByRole("button", { name: "Details" }).tap();
    await detail.getByRole("button", { name: "Watch execution" }).tap();
    await expect(detail.locator("iframe")).toHaveCount(1);
    await expect(detail.locator("iframe")).toHaveAttribute("src", /youtube-nocookie\.com\/embed\//);
    await page.setViewportSize({ width: 640, height: 320 });
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
    await page.setViewportSize(portrait);
    await page.screenshot({ path: testInfo.outputPath("inline-video.png"), animations: "disabled" });
    await detail.getByRole("button", { name: "Close exercise details" }).tap();
    await expect(page.locator("iframe")).toHaveCount(0);
    await squat.getByRole("checkbox", { name: /Complete Agachamento goblet/i }).tap();
    await expect(squat.getByText(/Completed · tap circle to undo/)).toBeVisible();
    await expect(squat.locator(".rest-suggestion")).toBeVisible();
    await squat.getByRole("button", { name: /Start \d+:/ }).tap();
    const bar = page.getByRole("group", { name: "Rest timer" });
    await expect(bar).toBeVisible();
    await expect(page.locator(".rest-timer-bar")).toBeInViewport();
    await page.screenshot({ path: testInfo.outputPath("compact-timer.png"), animations: "disabled" });
    await bar.getByRole("button", { name: /Rest/ }).tap();
    const timer = page.getByRole("dialog", { name: "Rest timer" });
    await expect(timer).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath("rest-timer.png"), animations: "disabled" });
    await timer.getByRole("button", { name: "+30 sec", exact: true }).tap();
    await timer.getByRole("button", { name: "Pause" }).tap();
    await timer.getByRole("button", { name: "Resume" }).tap();
    await timer.getByRole("button", { name: "Close rest timer" }).tap();
    await page.getByRole("link", { name: "Home", exact: true }).tap();
    await expect(page).toHaveURL("http://localhost:3000/");
    await expect(bar).toBeVisible();
    await page.reload();
    await expect(bar).toBeVisible();
    await page.evaluate(() => { const key = "treino-local:v2"; const data = JSON.parse(localStorage.getItem(key)!); data.restTimer.targetEndAt = new Date(Date.now() - 1_000).toISOString(); localStorage.setItem(key, JSON.stringify(data)); });
    await page.reload();
    await expect(bar.getByText("Rest complete")).toBeVisible();
    await bar.getByRole("button", { name: "Done" }).tap();
    await page.getByRole("button", { name: "Open workout" }).first().tap();
    await squat.getByRole("button", { name: /Start \d+:/ }).tap();
    await expect(bar).toBeVisible();
    await page.getByRole("link", { name: /Finish workout/ }).tap();
    await page.getByRole("textbox", { name: /WORKOUT NOTE/ }).fill("Workout felt good; increased load.");
    await page.screenshot({ path: testInfo.outputPath("finish-note.png"), animations: "disabled" });
    await page.getByRole("button", { name: /Save workout/ }).tap();
    await page.getByRole("link", { name: "Not now" }).tap();
    await expect(page.locator(".history-note-preview")).toContainText("Workout felt good");
    await page.locator(".history-card").first().tap();
    await expect(page.getByText("Workout felt good; increased load.")).toBeVisible();
    await expect(page.locator(".rest-timer-bar")).toHaveCount(0);
    await page.screenshot({ path: testInfo.outputPath("history-with-workout-note.png"), animations: "disabled" });
    await page.getByRole("link", { name: "Home", exact: true }).tap();
    await expect(page).toHaveURL("http://localhost:3000/");
    await page.getByRole("button", { name: "Start workout" }).first().tap();
    await squat.getByRole("button", { name: "Details" }).tap();
    await detail.getByRole("tab", { name: "History" }).tap();
    await expect(detail.getByText("Highest comparable load")).toBeVisible();
  } finally { await rm(folder, { recursive: true, force: true }); }
});
